Repository maityamit/Sleepometer-Android-App, pull requests merged in 2022-10, with the labels that each got.

#24 issue #19 Emoji icon in sleep score
  .idea/misc.xml
  README.md
  app/src/main/java/sleepometerbyamitmaity/example/sleepometer/HomeFragment.java
  app/src/main/res/layout/fragment_home.xml
Labels: PR: reviewed-approved, hacktoberfest

#25 added Dialog
  app/src/main/java/sleepometerbyamitmaity/example/sleepometer/HomeFragment.java
  app/src/main/res/drawable/ic_baseline_info_24.xml
  app/src/main/res/layout/app_dialog.xml
  app/src/main/res/layout/fragment_home.xml
Labels: PR: unreviewed, hacktoberfest, hacktoberfest-accepted

#27 Alarm Bug fixed
  app/src/main/AndroidManifest.xml
  app/src/main/java/sleepometerbyamitmaity/example/sleepometer/HomeFragment.java
Labels: bug, PR: unreviewed, hacktoberfest, hacktoberfest-accepted

#29 Updated Contributing.md file
  CONTRIBUTING.md
Labels: PR: unreviewed, hacktoberfest, hacktoberfest-accepted
