Repository maityamit/Sleepometer-Android-App, pull requests merged in 2022-07, with the labels that each got.

#9 changed background color
  .idea/.name
  .idea/compiler.xml
  .idea/deploymentTargetDropDown.xml
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/res/drawable/window_background.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_splash_screen.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/layout/fragment_stats.xml
Labels: PR: reviewed-approved, HSOC22-Level-1, HCSOC22

#12 Splash redesign
  app/src/main/java/sleepometerbyamitmaity/example/sleepometer/SplashScreenActivity.java
  app/src/main/res/anim/welcome_bottom_animation.xml
  app/src/main/res/anim/welcome_top_animation.xml
  app/src/main/res/layout/activity_splash_screen.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: PR: unreviewed, HSOC22-Level-1, HCSOC22

#13 some ui cghanges done
  .idea/vcs.xml
  app/src/main/res/layout/fragment_home.xml
Labels: PR: unreviewed, HSOC22-Level-2, HCSOC22

#14 added alarm feature
  .idea/misc.xml
  .idea/vcs.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/sleepometerbyamitmaity/example/sleepometer/Alarm.java
  app/src/main/java/sleepometerbyamitmaity/example/sleepometer/AlarmReceiver.java
  app/src/main/java/sleepometerbyamitmaity/example/sleepometer/HomeFragment.java
  app/src/main/res/drawable/clock.png
  app/src/main/res/layout/activity_alarm.xml
  app/src/main/res/layout/fragment_home.xml
Labels: PR: unreviewed, HSOC22-Level-3, HSOC22
