Repository maityamit/Sleepometer-Android-App, pull requests merged in 2022-12, with the labels that each got.

#32 basic changes - (Folder arrangment)
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/sleepometerbyamitmaity/example/sleepometer/Alarm.java
  app/src/main/java/sleepometerbyamitmaity/example/sleepometer/MainActivity.java
  app/src/main/java/sleepometerbyamitmaity/example/sleepometer/ProfileActivity.java
  app/src/main/java/sleepometerbyamitmaity/example/sleepometer/Users.java
  app/src/main/java/sleepometerbyamitmaity/example/sleepometer/alarmBroadcastReceiver/AlarmReceiver.java
  app/src/main/java/sleepometerbyamitmaity/example/sleepometer/fragments/HomeFragment.java
  app/src/main/java/sleepometerbyamitmaity/example/sleepometer/fragments/SettingsFragment.java
  app/src/main/java/sleepometerbyamitmaity/example/sleepometer/fragments/StatsFragment.java
  app/src/main/java/sleepometerbyamitmaity/example/sleepometer/modelClasses/Users.java
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/layout/fragment_stats.xml
Labels: PR: reviewed-approved

#35 Added Sleep Score percentage in HomeFragment at line 96. Issue #17
  app/src/main/java/sleepometerbyamitmaity/example/sleepometer/fragments/HomeFragment.java
Labels: PR: reviewed-approved

#39 #36 Feature: Live update Active sleep time
  app/src/main/java/sleepometerbyamitmaity/example/sleepometer/fragments/HomeFragment.java
Labels: PR: reviewed-approved, kwoc'22

#42 replace findViewById with viewBinding
  app/build.gradle
  app/src/main/java/sleepometerbyamitmaity/example/sleepometer/Alarm.java
  app/src/main/java/sleepometerbyamitmaity/example/sleepometer/LoginActivity.java
  app/src/main/java/sleepometerbyamitmaity/example/sleepometer/MainActivity.java
  app/src/main/java/sleepometerbyamitmaity/example/sleepometer/ProfileActivity.java
  app/src/main/java/sleepometerbyamitmaity/example/sleepometer/SplashScreenActivity.java
  app/src/main/java/sleepometerbyamitmaity/example/sleepometer/fragments/HomeFragment.java
  app/src/main/java/sleepometerbyamitmaity/example/sleepometer/fragments/SettingsFragment.java
  app/src/main/java/sleepometerbyamitmaity/example/sleepometer/fragments/StatsFragment.java
Labels: PR: reviewed-approved, kwoc'22

#45 Stats fragment crash fix using try catch block
  .idea/misc.xml
  app/src/main/java/sleepometerbyamitmaity/example/sleepometer/fragments/StatsFragment.java
Labels: PR: reviewed-approved, kwoc'22

#49 #48 applying INTENT on share , feedback and other option
  .idea/misc.xml
  app/src/main/java/sleepometerbyamitmaity/example/sleepometer/fragments/SettingsFragment.java
Labels: PR: unreviewed, kwoc'22

#50 #47 sleep score and Avg sleep duration update by fetching the data from backend
  app/src/main/java/sleepometerbyamitmaity/example/sleepometer/fragments/HomeFragment.java
  app/src/main/res/layout/fragment_home.xml
Labels: PR: unreviewed, kwoc'22

#52 #51 timePicker Added
  .idea/misc.xml
  app/src/main/java/sleepometerbyamitmaity/example/sleepometer/fragments/HomeFragment.java
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/time_pick_dialog.xml
Labels: PR: unreviewed
