Repository maityamit/Sleepometer-Android-App, pull requests merged in 2023-02, with the labels that each got.

#56 made changes in sleepscore button
  .idea/misc.xml
  app/google-services.json
  app/src/main/java/sleepometerbyamitmaity/example/sleepometer/fragments/HomeFragment.java
  app/src/main/res/layout/fragment_home.xml
Labels: PR: unreviewed, iwoc, medium

#58 Made the Miss Click button Null Safe
  app/google-services.json
  app/src/main/java/sleepometerbyamitmaity/example/sleepometer/fragments/HomeFragment.java
Labels: PR: unreviewed, iwoc, easy

#60 Settings fragment UI changed
  app/src/main/java/sleepometerbyamitmaity/example/sleepometer/fragments/SettingsFragment.java
  app/src/main/res/drawable/baseline_keyboard_arrow_right_24.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/values/colors.xml
Labels: PR: unreviewed, iwoc, medium

#65 UI
  app/src/main/java/sleepometerbyamitmaity/example/sleepometer/LoginActivity.java
  app/src/main/res/drawable/active_background.xml
  app/src/main/res/drawable/background_app.xml
  app/src/main/res/drawable/button_colour.xml
  app/src/main/res/drawable/ic_baseline_add_24.xml
  app/src/main/res/drawable/input_background.xml
  app/src/main/res/drawable/window_background.xml
  app/src/main/res/layout/activity_alarm.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/menu/bottom.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: PR: unreviewed, iwoc, easy

#67 Modified Google Sign in Button
  app/src/main/res/drawable/Google_Sign_in_Button.png
  app/src/main/res/drawable/google_sign_in_button_final.png
  app/src/main/res/layout/activity_login.xml
Labels: PR: unreviewed, iwoc, easy

#70 Changes in UI #69
  .idea/gradle.xml
  app/src/main/java/sleepometerbyamitmaity/example/sleepometer/LoginActivity.java
  app/src/main/res/drawable/g_login.png
  app/src/main/res/drawable/g_sign.png
  app/src/main/res/drawable/github.png
  app/src/main/res/drawable/github2.png
  app/src/main/res/drawable/github3.png
  app/src/main/res/drawable/github_logo.jpg
  app/src/main/res/drawable/linkedin.png
  app/src/main/res/drawable/linkedinlogo.png
  app/src/main/res/drawable/shape.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/layout/time_pick_dialog.xml
  app/src/main/res/values/strings.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  zz.txt
Labels: PR: unreviewed, iwoc, easy

#75 Update CONTRIBUTING.md
  CONTRIBUTING.md
  Demo/10.png
  Demo/11.jpg
  Demo/9.png
  FlowofControl.md
  README.md
Labels: PR: reviewed-approved, iwoc, Easy

#79 Update readme file
  README.md
Labels: PR: unreviewed, iwoc, Medium

#86 Rounded Corners
  .idea/gradle.xml
  app/src/main/res/drawable/googlesignin.png
  app/src/main/res/drawable/window_background.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/activity_splash_screen.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/progress_diaglog.xml
  app/src/main/res/layout/time_pick_dialog.xml
Labels: PR: unreviewed, iwoc, Easy

#83 added missing instruction on CONTRIBUTING.md
  .idea/gradle.xml
  CONTRIBUTING.md
Labels: PR: reviewed-approved, Easy, JWOC

#84 Workflow process aim
  README.md
Labels: PR: reviewed-approved, iwoc, Easy

#93 Fixed the application in portrait mode only to avoid crash. #89 #JWOC
  app/src/main/AndroidManifest.xml
Labels: PR: unreviewed, iwoc, Easy

#91 Now screen would not get dim unnecessarily
  app/src/main/java/sleepometerbyamitmaity/example/sleepometer/MainActivity.java
Labels: PR: unreviewed, iwoc, Medium
